CREATE TABLE blogs (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title varchar(255) NOT NULL,
    content text NOT NULL,
    author varchar(255) NOT NULL,
    created_at timestamptz DEFAULT NOW(),
    expires timestamptz NOT NULL
);

CREATE INDEX idx_blogs_created ON blogs (created_at);

CREATE TABLE users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    email varchar(255) NOT NULL UNIQUE,
    hashed_password char(60) NOT NULL,
    created timestamptz NOT NULL DEFAULT NOW()
);

INSERT INTO users (name, email, hashed_password)
    VALUES ('Webtest User', 'webtestuser@example.com', '$2a$12$NuTjWXm3KKntReFwyBVHyuf/to.HEwTy.eS206TNfkGfr6HzGJSWG');

